# Build stage
FROM golang:1.21-alpine AS builder
WORKDIR /app

# set env variables
ARG EMAIL_SENDER_NAME
ARG EMAIL_SENDER_ADDRESS
ARG EMAIL_SENDER_PASSWORD
ARG DB_SOURCE
ARG ENVIRONMENT
ARG RABBITMQ_SERVER_URL

ENV EMAIL_SENDER_NAME ${EMAIL_SENDER_NAME}
ENV EMAIL_SENDER_ADDRESS ${EMAIL_SENDER_ADDRESS}
ENV EMAIL_SENDER_PASSWORD ${EMAIL_SENDER_PASSWORD}
ENV DB_SOURCE ${DB_SOURCE}
ENV ENVIRONMENT ${ENVIRONMENT}
ENV RABBITMQ_SERVER_URL ${RABBITMQ_SERVER_URL}

COPY . .
RUN go build -o main main.go

RUN echo ${DB_SOURCE}

# Run stage
FROM alpine:3.16
WORKDIR /app

COPY --from=builder /app/main .

# Create .env file
RUN echo EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME} > .env && \
    echo EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS} >> .env && \
    echo EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD} >> .env && \
    echo DB_SOURCE=${DB_SOURCE} >> .env && \
    echo ENVIRONMENT=${ENVIRONMENT} >> .env && \
    echo RABBITMQ_SERVER_URL=${RABBITMQ_SERVER_URL} >> .env && \
    cat .env

COPY start.sh ./

EXPOSE 8080
CMD [ "/app/main" ]
ENTRYPOINT [ "/app/start.sh" ]
